//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXRibbon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DXRibbon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturi.
        /// </summary>
        internal static string BillListModule {
            get {
                return ResourceManager.GetString("BillListModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listă clienți.
        /// </summary>
        internal static string ClientsListModule {
            get {
                return ResourceManager.GetString("ClientsListModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documente.
        /// </summary>
        internal static string DocumentGroup {
            get {
                return ResourceManager.GetString("DocumentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        internal static string MetadataGroup {
            get {
                return ResourceManager.GetString("MetadataGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parteneri.
        /// </summary>
        internal static string PartenerGroup {
            get {
                return ResourceManager.GetString("PartenerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listă parteneri.
        /// </summary>
        internal static string PartnerListModule {
            get {
                return ResourceManager.GetString("PartnerListModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listă transportatori.
        /// </summary>
        internal static string TransportListModule {
            get {
                return ResourceManager.GetString("TransportListModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizatori.
        /// </summary>
        internal static string UserListModule {
            get {
                return ResourceManager.GetString("UserListModule", resourceCulture);
            }
        }
    }
}
